# Generated by Django 4.0.3 on 2022-04-06 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ai_one',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('current', models.DecimalField(decimal_places=5, max_digits=5, verbose_name='current')),
                ('sts', models.IntegerField(choices=[(1, 1), (0, 0), (2, 2)], max_length=2)),
            ],
        ),
    ]
