# Generated by Django 4.0.3 on 2022-04-06 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagrams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ai_one',
            name='current',
            field=models.DecimalField(decimal_places=3, max_digits=5, verbose_name='current'),
        ),
    ]
