# Generated by Django 4.0.3 on 2022-04-07 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagrams', '0004_ai_two_alter_ai_one_sts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Else',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='ai_one',
            name='sts',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2)]),
        ),
        migrations.AlterField(
            model_name='ai_two',
            name='sts',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2)]),
        ),
    ]
